version: '3.9'

networks:
 backend:
  external: true

services:
  postgre:
   image: postgres:13-alpine
   restart: always
   environment:
    POSTGRES_USER: postgre
    DB_SERVER_SCHEMA: zabbix
    POSTGRES_PASSWORD: passwd
    POSTGRES_DB: zabbix
    POSTGRES_HOST_AUTH_METHOD: trust
   networks:
    - backend

  zabbix_web:
   image: zabbix/zabbix-web-nginx-pgsql
   environment:
    ZBX_SERVER_HOST: zabbix_server
    ZBX_SERVER_PORT: 10051
    POSTGRES_DB: zabbix
    DB_SERVER_HOST: postgre
    DB_SERVER_PORT: 5432
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: passwd
    DB_SERVER_SCHEMA: postgre
   ports:
    - 8081:8080
   networks:
    - backend

  zabbix_server:
   image: zabbix/zabbix-server-pgsql
   environment:
    POSTGRES_DB: zabbix
    DB_SERVER_HOST: postgre
    DB_SERVER_PORT: 5432
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: passwd
    DB_SERVER_SCHEMA: postgre
   networks:
    - backend

  zabbix_agent:
   image: zabbix/zabbix-agent
   environment:
    ZBX_SERVER_HOST: zabbix_server
   volumes:
    - /dev/sda1:/dev/sda5
    - /dev/sda2:/dev/sda6
    - /dev/sda5:/dev/sda7 
   ports:
    - 10050:10050 
   networks:
    - backend