version: '3.9'

networks:
 backend:
  external: true

services:
  postgre:
   image: postgres:13-alpine
   restart: always
   environment:
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: passwd
    POSTGRES_DB: test
    POSTGRES_HOST_AUTH_METHOD: trust
   networks:
    - backend
  zabix:
   image: zabbix/zabbix-web-nginx-pgsql
   environment:
    ZBX_SERVER_HOST: zab_serv
    ZBX_SERVER_PORT: 10051
    POSTGRES_DB: test
    DB_SERVER_HOST: postgre
    DB_SERVER_PORT: 5432
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: passwd
   ports:
    - 8081:8080
   networks:
    - backend

  zab_serv:
   image: zabbix/zabbix-server-pgsql
   environment:
    POSTGRES_DB: test
    DB_SERVER_HOST: postgre
    DB_SERVER_PORT: 5432
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: passwd
   ports:
    - 8080:8200
   networks:
    - backend
